### ISSUE TITLE
The download link can be confusing (for users who do not belong to macOS)

### ISSUE THREAD

**Issue by markozxuu** [vercel/now-desktop#549]
## Issue

For users who are not of `MacOS` it can be a bit confusing to access the download page. there is not something that visually tells you that you are downloading the correct version in your operating system.
![44464975_1919287478376417_6725364653150437376_n](https://user-images.githubusercontent.com/16585386/47272846-cee4c800-d550-11e8-9a40-f72389a11dc6.png)

Report: https://spectrum.chat/?t=b91ca633-cd31-4c54-bdf3-5be3d2286432

## Possible solution

That must be solved simply by adding an icon to the download link so that the user can see a difference.

Example:
![44536012_491945051308957_8172361675161206784_n](https://user-images.githubusercontent.com/16585386/47273006-2421d900-d553-11e8-8d5f-c65671e15cce.png)

cc @evilrabbit @leo @rauchg

**Comment by Korkman** [comment]
In fact, it did download the macOS version for me on Firefox Windows yesterday.

**Comment by imam** [comment]
I can't download the windows version, any help?

**Comment by MAPESO** [comment]
@imam This solution would help for now 🙏 
https://github.com/zeit/now-desktop/releases
<img width="1275" alt="screen shot 2019-02-25 at 21 34 22" src="https://user-images.githubusercontent.com/16585386/53386200-e2f96580-3946-11e9-8422-471168bca5e8.png">

**Comment by juliangruber** [comment]
Related to https://github.com/zeit/now-desktop/issues/587
